name: "Checks om merge request"

on:
  pull_request:
    branches:
      - main 
jobs:
  release:
    name: Checks before merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install node & yarn 
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Install packages
        run: npm install

      - name: Test library
        run: npm run lint && npm run type-check

      - name: Build library
        run: npm run build