name: "Publish to npm"

on:
  push:
    branches:
      - main 
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Install node & yarn 
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Install third party libs
        run: npm install

      - name: Build library
        run: npm run build

      - name: Test library
        run: npm run lint && npm run type-check

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}